### PR TITLE
Update sensor.py

### PR DESCRIPTION
**Pull request by wjaceh**
Region "EE" (Estonia) was missing.

### CODE REVIEW

**Comment by Hellowlol** [comment]
Oops, must have slipped pass me. Thanks!

**Comment by wjaceh** [comment]
It's a great tool. Thanks for your effort!
Would you add some features (I'm weak on coding) to include some extra price components (tariffs) so the actual electricity end cost would be shown?
I understand that different countries have different tariff models and customers have different service provider packets but maybe some generic model could be made.
I would be happy to thing along and provide with you some examples.

**Comment by Hellowlol** [comment]
I dont think in willing to do this as it would be to much work. Your best bet would be create template sensor where you use the price from nordpool and add any tariffs there.

Can you give me a example of a tariff?

**Comment by wjaceh** [comment]
> I dont think in willing to do this as it would be to much work. Your best bet would be tocreate template sensor where you use the price from nordpool and add any tariffs there.
> 
> Can you give me a example of a tariff?

I had it done in Openhab rules but can't access the configuration at the moment.
It is built up like this:
1kWh/price with VAT

**day:** | [Nordpool price (_0.030_)+ operator margin (0.001)+   electricity tariff (0.00447)+ renewable energy tariff (0.0104)+ network fee   (0.0423)]*VAT (1.2)
**night:** | [Nordpool price (_0.030_)+ operator margin (0.001)+   electricity tariff (0.00447)+ renewable energy tariff (0.0104)+ network fee   (0.0246)]*VAT (1.2)

Time zone | day | 07:00 | 23:00 | Monday-Friday
Time zone | night | 23:00 | 07:00 | Monday-Saturday
Summer time | day | 08:00 | 00:00 | Monday-Friday
Summer time | night | 00:00 | 08:00 | Monday-Saturday

**Comment by Hellowlol** [comment]
I tries to make a template but dunno if it will work as expected.

````
{% macro calc(v) -%}
 {%set d = {"operator_margin": 0.001,
            "electricity_tariff": 0.00447,
            "renewable_tariff": 0.0104,
            "nw_fee_night": 0.0246,
            "nw_fee_day": 0.0423
  } %}
 {%set day_price = v + d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_day * 1.2 | float%}
{%set night_price = v + d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_night * 1.2 | float%}
 {% if now().timetuple().tm_isdst == 1%}
  {% if now().hour > 8 %}
  {{day_price}}
  {% else %}
    {{night_price}}
  {% endif %}
 {% else %}
   {% if now().hour >= 7 and now().hour < 23%}
     {{day_price}}
   {% else %}
     {{night_price}}
   {% endif %}
{% endif %}
{%- endmacro %}

{{calc(1)}}
````

**Comment by wjaceh** [comment]
> I tries to make a template but dunno if it will work as expected.
> 
> ```
> {% macro calc(v) -%}
>  {%set d = {"operator_margin": 0.001,
>             "electricity_tariff": 0.00447,
>             "renewable_tariff": 0.0104,
>             "nw_fee_night": 0.0246,
>             "nw_fee_day": 0.0423
>   } %}
>  {%set day_price = v + d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_day * 1.2 | float%}
> {%set night_price = v + d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_night * 1.2 | float%}
>  {% if now().timetuple().tm_isdst == 1%}
>   {% if now().hour > 8 %}
>   {{day_price}}
>   {% else %}
>     {{night_price}}
>   {% endif %}
>  {% else %}
>    {% if now().hour >= 7 and now().hour < 23%}
>      {{day_price}}
>    {% else %}
>      {{night_price}}
>    {% endif %}
> {% endif %}
> {%- endmacro %}
> 
> {{calc(1)}}
> ```

Hei, thank you!
I owe you a beer :)
I will test it out. 
I haven't googled the timetuple() and tm_isdst functions yet.
Do they take into account that weekend days are considered also as "night?
Time zone | day | 07:00 | 23:00 | Monday-Friday
Time zone | night | 23:00 | 07:00 | Monday-**Saturday**
Summer time | day | 08:00 | 00:00 | Monday-Friday
Summer time | night | 00:00 | 08:00 | Monday-**Saturday**

**Comment by Hellowlol** [comment]
Dst is summer time. My example does Nottingham regarding the days. What about Sunday? Free power? 😂

**Comment by wjaceh** [comment]
> Dst is summer time. My example does Nottingham regarding the days. What about Sunday? Free power? 😂

I wish it was :)
Saturday and Sunday always have the night tariff.

**Comment by wjaceh** [comment]
How can I offset the nordpool value by 1 hour?
Currently I get it by CET/CEST time. I need to get it as EET/EEST.

**Comment by Hellowlol** [comment]
The timezone should be the timezone that is set in homeassistant. Or are you using home assistant a timezone but needs prices in another timezone?

**Comment by wjaceh** [comment]
> The timezone should be the timezone that is set in homeassistant. Or are you using home assistant a timezone but needs prices in another timezone?

I have the correct time zone in HA configuration:
image

Nordpool gives price according to different time zone (CEST):
image

which is 1h behind from what I need:
image

I shoudl get 66,85€/MWh

**Comment by turpela** [comment]
I get nordpool values 1 hour ahead, nordpool currently show next hour value. Timezone setup in homeassistant:
time_zone: Europe/Helsinki

and nordpool setting:
 - platform: nordpool

    region: "FI"

**Comment by wjaceh** [comment]
> I get nordpool values 1 hour ahead, nordpool currently show next hour value. Timezone setup in homeassistant:
> time_zone: Europe/Helsinki
> 
> and nordpool setting:
> 
> * platform: nordpool
>   region: "FI"

so you also have it 1h off from what it should be, right?

**Comment by Hellowlol** [comment]
Can you open a issue regarding this? I’m not sure thy this is happening but I think it might be related to a fix when the api returns junk (missing values)

**Comment by wjaceh** [comment]
> Can you open a issue regarding this? I’m not sure thy this is happening but I think it might be related to a fix when the api returns junk (missing values)

If the time zone didn't come through then shouldn't it be off at the other direction (UTC)?

**Comment by Hellowlol** [comment]
The current price just grabs the current price from a list that is that sorted from oldest to newest and we just the current hour to grab the "correct" hour. I guess i have messed something up regarding that.

**Comment by wjaceh** [comment]
> The current price just grabs the current price from a list that is that sorted from oldest to newest and we just the current hour to grab the "correct" hour. I guess i have messed something up regarding that.

Could it be that utcnow() should be used as otherwise you apply time zone to time zone.
image

image

**Comment by Hellowlol** [comment]
No, that should be related to that problem. Can you run this see if you get the correct price?

https://repl.it/@Hellowlol/DimgreyEmptyDevelopment

**Comment by wjaceh** [comment]
> No, that should be related to that problem. Can you run this see if you get the correct price?
> 
> https://repl.it/@Hellowlol/DimgreyEmptyDevelopment

It is identical with the nordpool database and hasn't shifted it 

image

image

**Comment by Hellowlol** [comment]
So it the price correct or not? :P

**Comment by wjaceh** [comment]
> So it the price correct or not? :P

No it should be 1 hour behind= 61,79.
As in Sweden 17:00-18:00

**Comment by Hellowlol** [comment]
I dont understand why this fails. Can you post the output of the script?

**Comment by wjaceh** [comment]
> I dont understand why this fails. Can you post the output of the script?

can you instruct how it is done?
I'm quite new to HA and python

**Comment by Hellowlol** [comment]
You can just click run button on the link i gave you.

**Comment by wjaceh** [comment]
> You can just click run button on the link i gave you.

Ok, I thought that you want some sort of component debug log.

`Python 3.7.4 (default, Jul  9 2019, 00:06:43)
[GCC 6.3.0 20170516] on linux


Repl.it: Installing fresh packages

Collecting nordpool
  Downloading https://files.pythonhosted.org/packages/17/53/b16bd4b95561ee6b83970dbc531174559365ff9a28d19da6f81cc153facf/nordpool-0.2.tar.gz
Collecting pendulum
  Downloading https://files.pythonhosted.org/packages/0b/db/eadff08d7a50a5a28d13efba6a029868f72b662f7cb30079f4af56a8de02/pendulum-2.0.5-cp37-cp37m-manylinux1_x86_64.whl (141kB)
Requirement already satisfied: python-dateutil>=2.6.1 in ./.local/share/virtualenvs/python3/lib/python3.7/site-packages (from nordpool) (2.8.0)
Collecting pytz>=2017.2 (from nordpool)
  Downloading https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl (508kB)
Requirement already satisfied: requests>=2.18.4 in ./.local/share/virtualenvs/python3/lib/python3.7/site-packages (from nordpool)(2.22.0)
Collecting pytzdata>=2018.3 (from pendulum)
  Downloading https://files.pythonhosted.org/packages/7f/f9/cdd39831b0465285c02ed90cfbf0db25bb951cb2a35ded0e69222375bea3/pytzdata-2019.3-py2.py3-none-any.whl (489kB)
Requirement already satisfied: six>=1.5 in ./.local/share/virtualenvs/python3/lib/python3.7/site-packages (from python-dateutil>=2.6.1->nordpool) (1.12.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.local/share/virtualenvs/python3/lib/python3.7/site-packages (from requests>=2.18.4->nordpool) (1.25.5)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/share/virtualenvs/python3/lib/python3.7/site-packages (from requests>=2.18.4->nordpool) (2019.9.11)
Requirement already satisfied: idna<2.9,>=2.5 in ./.local/share/virtualenvs/python3/lib/python3.7/site-packages (from requests>=2.18.4->nordpool) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/share/virtualenvs/python3/lib/python3.7/site-packages (from requests>=2.18.4->nordpool) (3.0.4)
Installing collected packages: pytz, nordpool, pytzdata, pendulum
  Running setup.py install for nordpool: started
    Running setup.py install for nordpool: finished with status 'done'
Successfully installed nordpool-0.2 pendulum-2.0.5 pytz-2019.2 pytzdata-2019.3
You are using pip version 19.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
org now 2019-09-23T16:31:23.423675+00:00
Europe/Tallinn
current price for this hour (2019-09-23T19:31:23.410933+03:00) is 68.67
0 2019-09-22 22:00:00+00:00 28.51
1 2019-09-22 23:00:00+00:00 27.2
2 2019-09-23 00:00:00+00:00 27.38
3 2019-09-23 01:00:00+00:00 27.31
4 2019-09-23 02:00:00+00:00 27.6
5 2019-09-23 03:00:00+00:00 44.9
6 2019-09-23 04:00:00+00:00 58.37
7 2019-09-23 05:00:00+00:00 64.39
8 2019-09-23 06:00:00+00:00 69.8
9 2019-09-23 07:00:00+00:00 69.72
10 2019-09-23 08:00:00+00:00 70.11
11 2019-09-23 09:00:00+00:00 68.86
12 2019-09-23 10:00:00+00:00 64.99
13 2019-09-23 11:00:00+00:00 66.85
14 2019-09-23 12:00:00+00:00 51.11
15 2019-09-23 13:00:00+00:00 54.93
16 2019-09-23 14:00:00+00:00 62.21
17 2019-09-23 15:00:00+00:00 61.79
18 2019-09-23 16:00:00+00:00 66.88
19 2019-09-23 17:00:00+00:00 68.67
20 2019-09-23 18:00:00+00:00 51.83
21 2019-09-23 19:00:00+00:00 46.37
22 2019-09-23 20:00:00+00:00 44.93
23 2019-09-23 21:00:00+00:00 35.05`

**Comment by Hellowlol** [comment]
Can you update to the lastest version and add

````
logger:
  default: critical
  logs:
    custom_components.nordpool: debug
````
to your configuration.yaml and post your log.

**Comment by wjaceh** [comment]
> Can you update to the lastest version and add
> 
> ```
> logger:
>   default: critical
>   logs:
>     custom_components.nordpool: debug
> ```
> 
> to your configuration.yaml and post your log.

It is updated to latest version now.
Debug level I had already set, but for some reason I still get only INFO level events.

**Comment by wjaceh** [comment]
> I added the info i wanted ar info level so that dosent matter. Can you post the log?

2019-09-24 15:38:53 INFO (SyncWorker_2) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:39:22 INFO (SyncWorker_11) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:39:24 INFO (SyncWorker_2) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:39:53 INFO (SyncWorker_6) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:39:55 INFO (SyncWorker_9) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:40:24 INFO (SyncWorker_9) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:40:26 INFO (SyncWorker_18) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:40:55 INFO (SyncWorker_0) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:40:57 INFO (SyncWorker_5) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:41:26 INFO (SyncWorker_1) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:41:28 INFO (SyncWorker_5) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:41:57 INFO (SyncWorker_13) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:41:59 INFO (SyncWorker_11) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:42:28 INFO (SyncWorker_7) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:42:30 INFO (SyncWorker_16) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:42:59 INFO (SyncWorker_10) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:43:01 INFO (SyncWorker_5) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:43:30 INFO (SyncWorker_3) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:43:32 INFO (SyncWorker_5) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:44:01 INFO (SyncWorker_16) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:44:03 INFO (SyncWorker_19) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:44:32 INFO (SyncWorker_0) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:44:34 INFO (SyncWorker_4) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.

**Comment by wjaceh** [comment]
after reboot:
2019-09-24 15:49:16 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for nordpool which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-24 15:49:16 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-24 15:49:24 DEBUG (SyncWorker_10) [homeassistant.components.modbus] Setting up hub: OrderedDict([('name', 'hub1'), ('type', 'serial'), ('method', 'rtu'), ('port', '/dev/ttyUSB0'), ('baudrate', 9600), ('stopbits', 1), ('bytesize', 8), ('parity', 'N'), ('timeout', 3.0)])
2019-09-24 15:49:27 INFO (SyncWorker_12) [custom_components.nordpool] async_setup nordpool
2019-09-24 15:49:49 INFO (SyncWorker_18) [custom_components.nordpool.sensor] setup_platform OrderedDict([('platform', 'nordpool'), ('VAT', <function Boolean at 0x7fb29f4a70>), ('currency', 'EUR'), ('low_price_cutoff', 0.95), ('region', 'EE'), ('precision', 4), ('price_type', 'kWh'), ('friendly_name', 'Elektri börsihind')])
2019-09-24 15:49:50 INFO (SyncWorker_18) [custom_components.nordpool.sensor] pendulum default timezone Europe/Tallinn
2019-09-24 15:49:50 INFO (SyncWorker_18) [custom_components.nordpool.sensor] timezone set in ha <DstTzInfo 'Europe/Tallinn' LMT+1:39:00 STD>
2019-09-24 15:49:51 INFO (MainThread) [custom_components.nordpool.sensor] api returned junk infinty None
2019-09-24 15:49:51 INFO (MainThread) [custom_components.nordpool.sensor] api returned junk infinty None
2019-09-24 15:49:51 INFO (MainThread) [custom_components.nordpool.sensor] api returned junk infinty None
2019-09-24 15:49:54 INFO (MainThread) [custom_components.nordpool.sensor] api returned junk infinty None
2019-09-24 15:49:54 INFO (MainThread) [custom_components.nordpool.sensor] api returned junk infinty None
2019-09-24 15:49:54 INFO (MainThread) [custom_components.nordpool.sensor] api returned junk infinty None
2019-09-24 15:50:22 INFO (SyncWorker_5) [custom_components.nordpool.sensor] NordpoolSensor _data_today is none, trying to fetch it.
2019-09-24 15:50:24 INFO (SyncWorker_5) [custom_components.nordpool.sensor] Called _update setting attrs for the day
2019-09-24 15:50:24 INFO (SyncWorker_5) [custom_components.nordpool.sensor] NordpoolSensor _data_tomorrow is none, trying to fetch it.
2019-09-24 15:50:24 INFO (SyncWorker_5) [custom_components.nordpool.sensor] Updated _current_price!
2019-09-24 15:50:25 INFO (SyncWorker_0) [custom_components.nordpool.sensor] NordpoolSensor _data_today is none, trying to fetch it.
2019-09-24 15:50:25 INFO (SyncWorker_0) [custom_components.nordpool.sensor] Called _update setting attrs for the day
2019-09-24 15:50:25 INFO (SyncWorker_0) [custom_components.nordpool.sensor] NordpoolSensor _data_tomorrow is none, trying to fetch it.
2019-09-24 15:50:25 INFO (SyncWorker_0) [custom_components.nordpool.sensor] Updated _current_price!
2019-09-24 15:50:53 INFO (SyncWorker_8) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:50:56 INFO (SyncWorker_16) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-24 15:51:24 INFO (SyncWorker_19) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.

**Comment by Hellowlol** [comment]
Thanks!

**Comment by Hellowlol** [comment]
@turpela @wjaceh Should be OK now. Can you update and test if its correct now?

**Comment by wjaceh** [comment]
> @turpela @wjaceh Should be OK now. Can you update and test if its correct now?

I still have the same problem. Even uninstalled the component and conf and started over, but nothing.
here is the log:
2019-09-25 16:18:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-25 16:18:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for nordpool which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-25 16:18:15 DEBUG (SyncWorker_12) [homeassistant.components.modbus] Setting up hub: OrderedDict([('name', 'hub1'), ('type', 'serial'), ('method', 'rtu'), ('port', '/dev/ttyUSB0'), ('baudrate', 9600), ('stopbits', 1), ('bytesize', 8), ('parity', 'N'), ('timeout', 3.0)])
2019-09-25 16:18:27 INFO (SyncWorker_14) [custom_components.nordpool] async_setup nordpool
2019-09-25 16:18:51 INFO (MainThread) [custom_components.nordpool.sensor] api returned junk infinty None
2019-09-25 16:18:51 INFO (MainThread) [custom_components.nordpool.sensor] api returned junk infinty None
2019-09-25 16:18:51 INFO (MainThread) [custom_components.nordpool.sensor] api returned junk infinty None
2019-09-25 16:19:22 INFO (SyncWorker_9) [custom_components.nordpool.sensor] NordpoolSensor _data_today is none, trying to fetch it.
2019-09-25 16:19:25 INFO (SyncWorker_9) [custom_components.nordpool.sensor] Called _update setting attrs for the day
2019-09-25 16:19:25 INFO (SyncWorker_9) [custom_components.nordpool.sensor] NordpoolSensor _data_tomorrow is none, trying to fetch it.
2019-09-25 16:19:25 INFO (SyncWorker_9) [custom_components.nordpool.sensor] Updated _current_price!
2019-09-25 16:19:52 INFO (SyncWorker_15) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-25 16:20:23 INFO (SyncWorker_6) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.
2019-09-25 16:20:54 INFO (SyncWorker_2) [custom_components.nordpool.sensor] Tried to update the hourly price but it wasnt a new hour.

**Comment by Hellowlol** [comment]
Then i give up, i dont know why this fails, I set my timezone in windows to tallin. And it seems to be correct. EEST is cest +1 so it should be correct.

**Comment by wjaceh** [comment]
> Then i give up, i dont know why this fails, I set my timezone in windows to tallin. And it seems to be correct. EEST is cest +1 so it should be correct.

This is interesting. I wonder what is causing it. Do you think there could be some ways for this to happen when my configuration would be wrong? For example if there was some old sensor which was initially defined in another time zone and then deleted, but somehow nordpool component wouldn't let go of this variable. I did delete everything (component included) before the last test and then reinstalled them.

@turpela, did it solve your system problem? I would like to know it is components issue or mine.

**Comment by turpela** [comment]
Yes still having same problem, nordpool values are 1 hour ahead, with latest update.

**Comment by wjaceh** [comment]
> > I tries to make a template but dunno if it will work as expected.
> > ```
> > {% macro calc(v) -%}
> >  {%set d = {"operator_margin": 0.001,
> >             "electricity_tariff": 0.00447,
> >             "renewable_tariff": 0.0104,
> >             "nw_fee_night": 0.0246,
> >             "nw_fee_day": 0.0423
> >   } %}
> >  {%set day_price = v + d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_day * 1.2 | float%}
> > {%set night_price = v + d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_night * 1.2 | float%}
> >  {% if now().timetuple().tm_isdst == 1%}
> >   {% if now().hour > 8 %}
> >   {{day_price}}
> >   {% else %}
> >     {{night_price}}
> >   {% endif %}
> >  {% else %}
> >    {% if now().hour >= 7 and now().hour < 23%}
> >      {{day_price}}
> >    {% else %}
> >      {{night_price}}
> >    {% endif %}
> > {% endif %}
> > {%- endmacro %}
> > 
> > {{calc(1)}}
> > ```
> 
> Hei, thank you!
> I owe you a beer :)
> I will test it out.
> I haven't googled the timetuple() and tm_isdst functions yet.
> Do they take into account that weekend days are considered also as "night?
> Time zone | day | 07:00 | 23:00 | Monday-Friday
> Time zone | night | 23:00 | 07:00 | Monday-**Saturday**
> Summer time | day | 08:00 | 00:00 | Monday-Friday
> Summer time | night | 00:00 | 08:00 | Monday-**Saturday**

Hi,

can you help with the syntax a bit please (I'm quite new to programming):
I want to add extra condition so during weekends there would be night_price all the time.

`  - platform: template
    sensors:
      el_tariff:
        friendly_name: "Elektri tariifid km_ta"
        unit_of_measurement: '€/kWh'
        value_template: >-
          {% macro calc(v) -%}
           {%set d = {"operator_margin": 0.001,
                      "electricity_tariff": 0.00447,
                      "renewable_tariff": 0.0104,
                      "nw_fee_night": 0.0246,
                      "nw_fee_day": 0.0423
           } %}
          {%set day_price = v + ((d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_day) | float ) | round(4)%}
          {%set night_price = v + ((d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_night) | float ) | round(4)%}
          {% if now().timetuple().tm_isdst == 1 and now().weekday() >=0 and now().weekday() <6%}
           {% if now().hour > 8 %}
           {{day_price}}
           {% else %}
             {{night_price}}
           {% endif %}
          {% else %}
            {% if now().hour >= 7 and now().hour < 23% and now().weekday() >=0 and now().weekday() <6}
              {{day_price}}
            {% else %}
              {{night_price}}
            {% endif %}
          {% endif %}
          {%- endmacro %}

          {{calc(0)}}  `

can you spot the mistake ?

**Comment by wjaceh** [comment]
> > > I tries to make a template but dunno if it will work as expected.
> > > ```
> > > {% macro calc(v) -%}
> > >  {%set d = {"operator_margin": 0.001,
> > >             "electricity_tariff": 0.00447,
> > >             "renewable_tariff": 0.0104,
> > >             "nw_fee_night": 0.0246,
> > >             "nw_fee_day": 0.0423
> > >   } %}
> > >  {%set day_price = v + d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_day * 1.2 | float%}
> > > {%set night_price = v + d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_night * 1.2 | float%}
> > >  {% if now().timetuple().tm_isdst == 1%}
> > >   {% if now().hour > 8 %}
> > >   {{day_price}}
> > >   {% else %}
> > >     {{night_price}}
> > >   {% endif %}
> > >  {% else %}
> > >    {% if now().hour >= 7 and now().hour < 23%}
> > >      {{day_price}}
> > >    {% else %}
> > >      {{night_price}}
> > >    {% endif %}
> > > {% endif %}
> > > {%- endmacro %}
> > > 
> > > {{calc(1)}}
> > > ```
> > 
> > 
> > Hei, thank you!
> > I owe you a beer :)
> > I will test it out.
> > I haven't googled the timetuple() and tm_isdst functions yet.
> > Do they take into account that weekend days are considered also as "night?
> > Time zone | day | 07:00 | 23:00 | Monday-Friday
> > Time zone | night | 23:00 | 07:00 | Monday-**Saturday**
> > Summer time | day | 08:00 | 00:00 | Monday-Friday
> > Summer time | night | 00:00 | 08:00 | Monday-**Saturday**
> 
> Hi,
> 
> can you help with the syntax a bit please (I'm quite new to programming):
> I want to add extra condition so during weekends there would be night_price all the time.
> 
> ` - platform: template
> sensors:
> el_tariff:
> friendly_name: "Elektri tariifid km_ta"
> unit_of_measurement: '€/kWh'
> value_template: >-
> {% macro calc(v) -%}
> {%set d = {"operator_margin": 0.001,
> "electricity_tariff": 0.00447,
> "renewable_tariff": 0.0104,
> "nw_fee_night": 0.0246,
> "nw_fee_day": 0.0423
> } %}
> {%set day_price = v + ((d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_day) | float ) | round(4)%}
> {%set night_price = v + ((d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_night) | float ) | round(4)%}
> {% if now().timetuple().tm_isdst == 1 and now().weekday() >=0 and now().weekday() <6%}
> {% if now().hour > 8 %}
> {{day_price}}
> {% else %}
> {{night_price}}
> {% endif %}
> {% else %}
> {% if now().hour >= 7 and now().hour < 23% and now().weekday() >=0 and now().weekday() <6%}
> {{day_price}}
> {% else %}
> {{night_price}}
> {% endif %}
> {% endif %}
> {%- endmacro %}
> 
> ```
>       {{calc(0)}}  `
> ```
> 
> can you spot the mistake ?

Ok, maybe I got it.
There needs to be space after logic operator and 5 instead of 6, right?

`  - platform: template
    sensors:
      el_tariff:
        friendly_name: "Elektri tariifid km_ta"
        unit_of_measurement: '€/kWh'
        value_template: >-
          {% macro calc(v) -%}
           {%set d = {"operator_margin": 0.001,
                      "electricity_tariff": 0.00447,
                      "renewable_tariff": 0.0104,
                      "nw_fee_night": 0.0246,
                      "nw_fee_day": 0.0423
           } %}
          {%set day_price = v + ((d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_day) | float ) | round(4)%}
          {%set night_price = v + ((d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_night) | float ) | round(4)%}
          {% if now().timetuple().tm_isdst == 1 and now().weekday() >= 0 and now().weekday() < 5 %}
           {% if now().hour > 8 %}
           {{day_price}}
           {% else %}
             {{night_price}}
           {% endif %}
          {% else %}
            {% if now().hour >= 7 and now().hour < 23 and now().weekday() >= 0 and now().weekday() < 5%}
              {{day_price}}
            {% else %}
              {{night_price}}
            {% endif %}
          {% endif %}
          {%- endmacro %}

          {{calc(0)}} `

**Comment by nelgi** [comment]
i checked the on-line python at repl.it and it takes the wrong price, highlighted in green is what it should have taken:
image

verification with nordpoolspot (CET/CEST is always -1h compared to EET/EEST):
image

**Comment by nelgi** [comment]
the bug in the repl.it script in on line(s) 216-217, where the list l is re-sorted to x, and then value from x is fetched, using now.hour as the index to fetch from list x. but there will always be the 1h shift, as the list index starts from 0, but at index 0 we have price for EET 01:00 - 02:00, so query placed at 0:00-0:59 will actually fetch the price of 1:00 - 1:59 and so on.

**Comment by Hellowlol** [comment]
Update and see if the latest commit fixes your issue

**Comment by turpela** [comment]
Great. Now I'm getting correct price. TZ: Europe/Helsinki

**Comment by nelgi** [comment]
TZ: Europe/Tallinn is also correct now. Thank you!

**Comment by FreshLife22** [comment]
Hi.
TZ: Europe/Tallinn/EE. Data from Nordpool minus 1 hour. 
If see log file from HA, then also FI, LV, LT has same, minus 1 hour. 
In log file, first time data start from 22.00, not 23.00.
[home-assistant.log](https://github.com/custom-components/nordpool/files/8054263/home-assistant.log)

**Comment by FreshLife22** [comment]
[Nordpool data 12.02.2022 EE.xls](https://github.com/custom-components/nordpool/files/8067138/Nordpool.data.12.02.2022.EE.xls)
pic4

**Comment by Hellowlol** [comment]
@FreshLife22 I have no idea what you talking about. It you have a problem with the component open a new issue and use the issue template so I can get a clear understanding of the problem

**Pull request merged**
