### PR TITLE
Add community file for tariffs configurations

### LINKED ISSUE #92: Create wiki with Tariff configurations for providers or regions
**Is your feature request related to a problem? Please describe.**
I would like to create a correct tarriffs calculation that matches what I see in Denmark (provider: Modstrøm). This could be tricky, although I think most of the additional costs are fixed, and not varying by time of day or year.. 

**Describe the solution you'd like**
It could be awesome to have a pre-built list of tarriff configurations available, perhaps on a wiki or such. It could be contributed by users as they make the configurations to match.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by LordMike**
Added initial proposal for Denmark/Radius

Fixes #92

### CODE REVIEW

**Comment by Hellowlol** [comment]
Just make a wiki page for it.

**Comment by LordMike** [comment]
> Just make a wiki page for it.

Would love to - Github doesn't support the regular git flow for wiki pages. So I can prepare it, but I can't create a request for you to merge it in. :/

**Comment by LordMike** [comment]
The current config should work for DK/Radius - so wherever it needs to go, we can copy it there.. :)

**Comment by cnrd** [comment]
You are also missing the energinet tariffs, which are currently 11.229 øre/kWh

**Comment by LordMike** [comment]
They did not mention that with my energy company (modstrøm). 

-.-‘

**Comment by cnrd** [comment]
I am breaking it down here: https://reddit.com/r/Denmark/comments/p9hkkb/prisen_p%C3%A5_en_kwh_str%C3%B8m_er_for_uigennemskuelig/ if you want to know all the parts you are paying.

You are probably also paying something to modstrøm (avance) for each kWh.

My net company (Nettopower) takes 7 øre/kWh.

**Comment by Hellowlol** [comment]
I’m closing this as I don’t want the tariffs under version control. Add just add the code to the wikipage under this repo

**Comment by Allras82** [comment]
hi,

Iv made this tamplate for new tarriffs from 01-2023 in DK:

`      {% set s = {"fixed_cost": 0.125,
                  "tax": 0.008,
                  "low-cost_winter": 0.2038,
                  "high_load_winter": 0.6113,
                  "peek_load_winter": 1.8336,
                  "low-cost_summer": 0.2038,
                  "high_load_summer": 0.3056,
                  "peek_load_summer": 0.7945}%}
      {% if now().month >= 4 and now().month <10 %}
        {% if now().hour >=17 and now().hour <21 %} 
          {{s.peek_load_summer+s.fixed_cost+s.tax|float}}
        {% elif now().hour >=0 and now().hour <6 %}
          {{s.low-cost_summer+s.fixed_cost+s.tax|float}}
        {%else%} 
          {{s.high_load_summer+s.fixed_cost+s.tax|float}}
        {% endif %}
      {% else %}
        {% if now().hour >=17 and now().hour <21 %} 
            {{s.peek_load_winter+s.fixed_cost+s.tax|float}}
        {% elif now().hour >=0 and now().hour <6 %}
            {{s.low-cost_winter+s.fixed_cost+s.tax|float}}
        {%else%}
            {{s.high_load_winter+s.fixed_cost+s.tax|float}}
        {% endif %}
      {% endif %}`

but mi not sure how to use the template for aditional_cost.... did you make any description for that in the wiki?

**Comment by runemoennike** [comment]
Just in case it may help, the tariffs are available via Eloverblik.dk's API and I've added a PR for the eloverblik integration to fetch and expose them: https://github.com/JonasPed/homeassistant-eloverblik/pull/57

**Pull request closed without merging**
