### PR TITLE
Update Finnish VAT to 10%

### PR DESCRIPTION
**Pull request by ljungqvist**
The Finnish VAT will be 10% starting 2022-12-01. The VAT will go back to it's normal 24% again 2023-05-01.

### CODE REVIEW

**Comment by jeveli** [comment]
I have tested this about a month ago and can confirm it's working and is the easy to edit.

**Comment by ljungqvist** [comment]
One downside is that the default name sensor id changes. E.g. `sensor.nordpool_kwh_fi_eur_4_095_024` -> `sensor.nordpool_kwh_fi_eur_4_095_01`

**Comment by Hellowlol** [comment]
Hi

Thanks for the PR. Temporary vat changes will not be merged. Please use additional costs template to do you on vat calculations. See the readme for an example.

**Comment by Kirbo** [comment]
> Hi
> 
> Thanks for the PR. Temporary vat changes will not be merged. Please use additional costs template to do you on vat calculations. See the readme for an example.

Sorry for resurrecting old closed issue, but could you then at least remove the "Enable VAT" checkbox once and for all or at least add some tooltip/description/something next to it, that which percentage it uses.
I was happily using the integration and thought that the VAT is somehow being calculated correctly, but it clearly is not.
Now, as a workaround, I re-created the integration, disabled VAT and calculate the price via the Additional Cost input.

But anywho, for me, it makes no sense whatsoever to have both "Enable VAT" and "Additional Cost" input. It merely confuses the users.

**Pull request closed without merging**
